const menu = [
  {
    name: "New York-Style Pepperoni Pizza",
    vegetarian: "false",
    meat: "true",
    Unique: "false",
    PricePerSlice: 1.59,
    PricePerPie: 12.99,
    img: "https://external-preview.redd.it/gTPney1F7unUs2kqfoKGpEek42scx9Zc31QV2i8rrrQ.jpg?auto=webp&s=c1c40f28ad2529b4bb53e9864ef844a2bf68c72e",
    BestSeller: "true",
  },
  {
    name: "Chicago Deep-Dish Cheese Pizza",
    vegetarian: "true",
    meat: "false",
    Unique: "true",
    PricePerSlice: 5.19,
    PricePerPie: 25.99,
    img: "https://giordanos.com/wp-content/uploads/Hero-image_1210-v2.jpg",
    BestSeller: "true",
  },
  {
    name: "Pan Pizza",
    vegetarian: "true",
    meat: "false",
    Unique: "false",
    PricePerSlice: 3.59,
    PricePerPie: 22.59,
    img: "https://www.foodandwine.com/thmb/0d5iKJ0FNBRddr14VOOFDH8Ccc8=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/pizza-hut-pan-pizza-FT-BLOG0519-8c22665558d84c1c907c17e4188a1ac4.jpg",
    BestSeller: "false",
  },
  {
    name: "Ohio-Style Pickle Pizza",
    vegetarian: "true",
    meat: "false",
    Unique: "true",
    PricePerSlice: 6.99,
    PricePerPie: 20.39,
    img: "https://i.insider.com/5cbf5c1abd1e2754a34cd443?width=1136&format=jpeg",
    BestSeller: "true",
  },
  {
    name: "Stuffed Crust Pepperoni Pizza",
    vegetarian: "false",
    meat: "false",
    Unique: "false",
    PricePerSlice: 2.59,
    PricePerPie: 17.29,
    img: "https://www.sugarsaltmagic.com/wp-content/uploads/2020/03/Stuffed-Crust-Pepperoni-Pizza-1-500x500.jpg",
    BestSeller: "false",
  },
  {
    name: "Hawaiian Pizza",
    vegetarian: "false",
    meat: "true",
    Unique: "false",
    PricePerSlice: 3.09,
    PricePerPie: 19.59,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS26lFJPHymi7ZRj7PUM7RpjMcJj-7WiFwXgA&usqp=CAU",
    BestSeller: "false",
  },
  {
    name: "Deep-Fried Cheese Pizza",
    vegetarian: "true",
    meat: "false",
    Unique: "true",
    PricePerSlice: 2.59,
    PricePerPie: 13.99,
    img: "https://i.ytimg.com/vi/YXHJG10l76U/maxresdefault.jpg",
    BestSeller: "true",
  },
  {
    name: "St. Louis-Style Chicken Pizza",
    vegetarian: "false",
    meat: "true",
    Unique: "false",
    PricePerSlice: 3.99,
    PricePerPie: 20.59,
    img: "https://tmbidigitalassetsazure.blob.core.windows.net/rms3-prod/attachments/37/1200x1200/St--Louis-Style-Pizza_EXPS_FT20_258992_F_1217_1.jpg",
    BestSeller: "false",
  },
  {
    name: "Detriot-Style Pepperoni Pizza",
    vegetarian: "false",
    meat: "true",
    Unique: "false",
    PricePerSlice: 1.59,
    PricePerPie: 14.99,
    img: "https://cdn.vox-cdn.com/thumbor/UqiLpK321nAiox6fKPedIgTCpcs=/0x0:2000x1333/1200x800/filters:focal(952x522:1272x842)/cdn.vox-cdn.com/uploads/chorus_image/image/59946603/28563627225_f1484816ae_o.0.0.jpg",
    BestSeller: "false",
  },
  {
    name: "BBQ Chicken Pizza",
    vegetarian: "false",
    meat: "true",
    Unique: "true",
    PricePerSlice: 3.99,
    PricePerPie: 19.99,
    img: "https://www.southernliving.com/thmb/SUC7jw5joHEfiCpk3Hf0wOyoT3U=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/BBQ-Chicken-Pizza_WD0151-S-256b0bd90b294badb343211b3310160b.jpg",
    BestSeller: "false",
  },
  {
    name: "Anchovies Pizza",
    vegetarian: "false",
    meat: "true",
    Unique: "false",
    PricePerSlice: 1.19,
    PricePerPie: 9.99,
    img: "https://izzycooking.com/wp-content/uploads/2020/05/Anchovy-Pizza-thumbnail.jpg",
    BestSeller: "false",
  },
  {
    name: "No Cheese-No Sauce Pizza",
    vegetarian: "true",
    meat: "false",
    Unique: "true",
    PricePerSlice: 0.99,
    PricePerPie: 6.99,
    img: "https://images-gmi-pmc.edge-generalmills.com/4cb4c043-e72c-49cf-ba90-99bc4e76cd7b.jpg",
    BestSeller: "false",
  },
  {
    name: "Neopolitan Cheese Pizza",
    vegetarian: "true",
    meat: "false",
    Unique: "true",
    PricePerSlice: 4.99,
    PricePerPie: 19.95,
    img: "https://upload.wikimedia.org/wikipedia/commons/a/a3/Eq_it-na_pizza-margherita_sep2005_sml.jpg",
    BestSeller: "true",
  },
];

export { menu };
